[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "thijsj_simple_web"
version = "0.0.1"
dependencies = [
    "quart",
]

[project.scripts]
hello = "thijsj_simple_web:app"

